config/routes.rb
Rails.application.routes.draw do
  get 'feedbacks/new'
  get 'feedbacks/create'
  devise_for :users
  root to: "pages#home"
  resources :bookings
  resources :massages
  resources :users do
    resources :feedbacks, only: [:new, :create, :index, :destroy, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :massage, dependent: :destroy
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  validates :rating, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
  validates :rating, length: { maximum: 5 }
  validates :rating, length: { minimum: 1 }
  validates :rating, numericality: { greater_than_or_equal_to: 1 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
  validates :rating, inclusion: { in: 1..5 }
end

app/models/massage.rb
class Massage < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :time, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :massages, through: :bookings
  has_many :feedbacks, dependent: :destroy

  validates :email, presence: true, format: { with: /\A[\w+\-.]+@(gmail|yahoo|hotmail|outlook)\.[a-z]+\z/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.massage = Massage.find(params[:massage_id])
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:edit, :destroy, :update]

  def index
    @feedbacks = Feedback.all
  end

  def new
    @feedback = Feedback.new
    @user = User.find(params[:user_id])
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    @feedback = Feedback.find(params[:id])
    if @feedback.user == current_user # Vérifie si l'utilisateur actuel est le propriétaire du témoignage
      if @feedback.update(feedback_params)
        redirect_to user_feedbacks_path(@feedback.user), notice: 'Le témoignage a été modifier avec succès.'
      else
        render :edit
      end
    else
      redirect_to root_path, alert: "Vous n'êtes pas autorisé à effectuer cette action."
    end
  end

  def create
    @user = User.find(params[:user_id])
    @feedback = Feedback.new(feedback_params)
    @feedback.user = current_user
    if @feedback.save
      redirect_to user_feedbacks_path
    else
      render :new
    end
  end

  def destroy
    @feedback.destroy
    redirect_to user_feedbacks_path
  end

  private

  def feedback_params
    params.require(:feedback).permit(:rating, :comment, :name)
  end

  def set_feedback
    @feedback = Feedback.find(params[:id])
  end
end

app/controllers/massages_controller.rb
class MassagesController < ApplicationController
  before_action :set_massage, only: [:show, :edit, :update, :destroy]

  def massages
    @massages = Massage.where("name LIKE ?", "%#{params[:query]}%")
    render :index
  end

  def index
    @massages = Massage.all
  end

  def show
  end

  def new
    @massage = Massage.new
  end

  def create
    @massage = Massage.new(massage_params)
    @massage.user = current_user
    if @massage.save
      redirect_to massages_path(@massage)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @massage.update(massage_params)
    redirect_to massage_path(@massage)
  end

  def destroy
    @massage.destroy
    redirect_to massages_path
  end

  private

  def massage_params
    params.require(:massage).permit(:title, :time, :price, :description)
  end

  def set_massage
    @massage = Massage.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def useradmin
    user_signed_in? && current_user.role == "admin"
  end
end

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/edit.html.erb
<div class="form-inputs">
<%= simple_form_for [@user, @feedback], method: :put do |f| %>
    <%= f.input :name, label: :Nom %>
    <%= f.input :comment, label: :Commentaire %>
    <div class="star-rating">
      <% (1..5).each do |star| %>
        <input type="radio" id="star-<%= star %>" name="feedback[rating]" value="<%= star %>" <%= "checked" if star == @feedback.rating %> />
        <label for="star-<%= star %>">&#9733;</label>
      <% end %>
    </div>
    <%= f.submit "Modifier l'avis", class: "btn1" %>
  <% end %>
</div>

app/views/feedbacks/index.html.erb
<div class="add-feedback">
  <%= link_to "Ajouter un témoignage", new_user_feedback_path, class: "btn btn-primary" %>
</div>


<% @feedbacks.reverse_each do |feedback| %>
  <div class="feedback">
    <div class="rating">
      <% feedback.rating.times do %>
        <i class="fa fa-star"></i>
      <% end %>
    </div>
    <p><strong>Commentaire : </strong><%= feedback.comment %></p>
    <p><strong>De : </strong><%= feedback.name %></p>
    <% if feedback.user == current_user %>
      <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-bars"></i></button>
        <div class="dropdown-content">
          <a href="<%= edit_user_feedback_path(feedback.user, feedback) %>"><i class="fas fa-pencil-alt"></i>  Modifier</a>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/feedbacks/new.html.erb
<div class="form-inputs">
  <%= simple_form_for [@user, @feedback] do |f| %>
    <%= f.input :name, label: :Nom %>
    <%= f.input :comment, label: :Commentaire %>

  <div class="star-rating">
    <% (1..5).reverse_each do |star| %>
      <input type="radio" id="star-<%= star %>" name="feedback[rating]" value="<%= star %>" <%= "checked" if star == @feedback.rating %> />
      <label for="star-<%= star %>">&#9733;</label>
    <% end %>
  </div>

    <%= f.submit "Laisser un avis", class: "btn1" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Julien</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar'%>

    <%= yield %>
<%= render 'shared/footer'%>
  </body>
</html>

app/views/massages/edit.html.erb
<%= simple_form_for @massage do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :time  %>

  <%= f.submit "Create Massage", class: "btn btn-primary" %>
<% end %>

app/views/massages/index.html.erb
<%# <%= link_to "Crée un nouveau massage", new_massage_path %>  <br> 
<div>
  <% @massages.each do |massage| %>
    <div class="massage-card">
      <div class="massage-card__content">
        <h2 class="massage-card__title">
          <%= massage.title %>
        </h2>
        <p class="massage-card__description">
          <strong> Description:</strong> <br>
          <%= massage.description %>
        </p>
          <div class="massage-card__price-time">
            <p class="massage-card__time">Durée :
            <%= massage.time.strftime("%H:%M") %> heure</p>
            <strong><p class="massage-card__price">Prix :
            <%= massage.price %>€</p></strong>

          </div>
          <%= link_to "Réserver", massage, class: "btn btn-flat" %>
          <%# <%= #link_to "Modifier un massage", edit_massage_path(massage) %>
      </div>
    </div>
  <% end %>
    </div>
  </div>
</div><br>

app/views/massages/new.html.erb
<%= simple_form_for @massage do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.datetime_select :time, { ampm: true, minute_step: 15 } %>
  <%= f.submit "Create Massage", class: "btn btn-primary" %>
<% end %>

app/views/massages/show.html.erb
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/benefique972" style="min-width:320px;height:630px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1540544660406-6a69dacb2804?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1264&q=80);">
  <div class="container">
    <h1 class="undertitle">Rejoignez notre voyage vers une vie plus heureuse avec nos <strong>massages</strong> de bien-être !</h1>


    <%= link_to "Commencez", massages_path, class: "btn1" %>
  </div>
</div>
<br>
<div class="container">





  <div class="me">
    <h2>Qui sommes-nous</h2>
    <h4>Notre histoire</h4>
    <p>
      Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
      Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500,
      quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.
    </p>
    <br>
    <p>
    Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
    Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500,
    quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.
    </p>
  </div>
  <br>
<br>

<h1 class="title">Nos produits</h1><br>
  <div class="card-products">

    <div class="card-product">
      <img src="https://images.unsplash.com/photo-1654747780214-bbfbeb4fd64a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80" class="card-img-top" alt="..."><br>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn1">Go somewhere</a>
      </div>
    </div>

    <div class="card-product" >
      <img src="https://images.unsplash.com/photo-1654747780214-bbfbeb4fd64a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80" class="card-img-top" alt="..."><br>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn1">Go somewhere</a>
      </div>
    </div>

    <div class="card-product">
      <img src="https://images.unsplash.com/photo-1654747780214-bbfbeb4fd64a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80" class="card-img-top" alt="..."><br>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn1">Go somewhere</a>
      </div>
    </div>
  </div>



</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-text">
    <p>© BNFIQUE</p>
    <span class="pos"><i class="fa-sharp fa-solid fa-location-dot"></i></span>
    <p>324-325 Rue Paul Marie Valère, Fort de France, 97200</p>

    <i class="fa-solid fa-phone"></i>
    <p>06-96-26-39-98</p>
<i class="fa-solid fa-envelope"></i>
    <a href="" class="contact">Nous contacter</a>
  </div>

  <div class="footer-links">
    <p>Suivez-nous !</p>
    <a href="https://www.instagram.com/fonten_islands/"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com/in/julien-burlet-585a80132/"><i class="fab fa-linkedin"></i></a>
  </div>
 <div>
 <a href="">Mentions légales</a><br>
 <a href="">Conditions générales</a>
  </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

     <a href="/"><h1 class= "home-title"> Bnfique</h1></a>
       <div class="nav-1">
    <ul class="list-inline tabs-underlined">
        <% if user_signed_in? %>
      <li>
        <%= link_to "Accueil", root_path, class: "tab-underlined active" %>
      </li>
      <li>
        <%= link_to "Massages", massages_path, class: "tab-underlined active" %>
      </li>
      <li>
        <%= link_to "Témoignage", user_feedbacks_path(current_user), class: "tab-underlined active" %>
      </li>

    </ul>

          <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class:"tab-underlined active" %>
        <% else %>
          <%= link_to "Se connecter", new_user_session_path, class:"tab-underlined active" %> ou <%= link_to "S'enregistrer", new_user_registration_path, class:"tab-underlined active" %>
        <% end %>
    </div>
  </div>
</div>